# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/End-To-End-Walkthrough',
                'doc_host': 'https://blainewishart.github.io',
                'git_url': 'https://github.com/blainewishart/End-To-End-Walkthrough',
                'lib_path': 'End_To_End_Walkthrough'},
  'syms': {'End_To_End_Walkthrough.core': {'End_To_End_Walkthrough.core.foo': ('core.html#foo', 'End_To_End_Walkthrough/core.py')}}}
